#Plugin by INFOMCPE.RU(https://github.com/infomcpe)
#█──────██─█████─█─███─█─────█─███████─███████─█─█████─██─────██──────██───────██████─██████──█─────█─
#█─█████─██─███─██──█──██────█─█───────█─────█─█──███──█─█████─█─█████─█─████████████─█─────█─█─────█─
#█─█████─███─█─███──█──█─█───█─█───────█─────█─█─█─█─█─█─███████─█████─█─████████████─█─────█─█─────█─
#█──────█████─████──█──█──█──█─█████───█─────█─█─██─██─█─███████──────██─────████████─██████──█─────█─
#█─█████─████─████──█──█───█─█─█───────█─────█─█─█████─█─███████─███████─████████───█─█───█───█─────█─
#█─█████─████─████──█──█────██─█───────█─────█─█─█████─█─█████─█─███████─████████───█─█────█──█─────█─
#█──────█████─████─███─█─────█─█───────███████─█─█████─██─────██─███████───────██───█─█─────█──█████──
#█████████████████─────────────────────────────██████████████████████████████████████─────────────────


#↓Set language available: rus, eng
#↓Выбор языка доступно: rus, eng
lang: rus
---
 